name: Daily Commit

on:
  schedule:
    # 1 PM PST = 21:00 UTC
    - cron: '0 21 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git config --global pull.rebase true
          
      - name: Create commit
        id: commit
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          # Get the current date in ISO format
          DATE=$(date -u +"%Y-%m-%d")
          
          # Create commit message with date and changes summary
          CHANGES=$(git diff --staged --name-status | awk '{print $2}' | tr '\n' ', ')
          git commit -m "Daily automated commit [$DATE] [skip ci]

          Changes:
          $CHANGES"
          
      - name: Push changes
        if: steps.commit.outcome == 'success'
        run: |
          # Retry logic for git push
          MAX_RETRIES=3
          RETRY_COUNT=0
          
          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            if git pull --rebase && git push origin HEAD:${{ github.ref }}; then
              echo "Successfully pushed changes"
              exit 0
            else
              RETRY_COUNT=$((RETRY_COUNT + 1))
              if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
                echo "Failed to push after $MAX_RETRIES attempts"
                exit 1
              fi
              echo "Push failed, retrying in 10 seconds... (Attempt $RETRY_COUNT of $MAX_RETRIES)"
              sleep 10
            fi
          done 